MvcProjeKampi/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;

namespace MvcProjeKampi.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        ContactManager cm = new ContactManager(new EfContactDal());
        ContactValidator cv = new ContactValidator();
        public ActionResult Index()
        {
            var contactvalues = cm.GetList();
            return View(contactvalues);
        }

        public ActionResult GetContactDetails(int id)
        {
            var contactvalues = cm.GetByID(id);
            return View(contactvalues);
        }
        public PartialViewResult MessageListMenu()
        {
            return PartialView();
        }
    }
}

MvcProjeKampi/Controllers/MessageController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    [Authorize(Roles = "B")]
    public class MessageController : Controller
    {
        // GET: Message
        MessageManager mm = new MessageManager(new EfMessageDal());
        MessageValidator messagevalidator = new MessageValidator();

        public ActionResult Inbox(string p = "")
        {
            string parameter = (string)Session["AdminUserName"];
            var messagelist = mm.GetListInbox(parameter, p);
            if (string.IsNullOrEmpty(p))
            {
                messagelist = mm.GetListInbox(parameter);
            }


            return View(messagelist);
        }


        public ActionResult Sendbox()
        {
            string parameter = (string)Session["AdminUserName"];
            var messagelist = mm.GetListSendbox(parameter);
            return View(messagelist);
        }

        public ActionResult GetInboxMessageDetails(int id)
        {
            var messagevalues = mm.GetByID(id);
            return View(messagevalues);
        }

        public ActionResult GetSendboxMessageDetails(int id)
        {
            var messagevalues = mm.GetByID(id);
            return View(messagevalues);
        }

        [HttpGet]
        public ActionResult NewMessage()
        {

            return View();
        }
        [HttpPost]
        public ActionResult NewMessage(Message p, string parameter)
        {


            ValidationResult results = messagevalidator.Validate(p);
            string adminValue = (string)Session["AdminUserName"];
            if (parameter == "send")
            {
                if (results.IsValid)
                {
                    p.SenderMail = adminValue;
                    p.Draft = false;
                    p.MessageDate = DateTime.Parse(DateTime.Now.ToShortDateString());
                    mm.MessageAddBL(p);
                    Thread.Sleep(1500);
                    return RedirectToAction("Sendbox");
                }
                else
                {
                    foreach (var item in results.Errors)
                    {
                        ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                    }
                }
            }
            else if (parameter == "draft")
            {
                if (results.IsValid)
                {
                    p.SenderMail = adminValue;
                    p.Draft = true;
                    p.MessageDate = DateTime.Parse(DateTime.Now.ToShortDateString());
                    mm.MessageAddBL(p);
                    Thread.Sleep(1500);
                    return RedirectToAction("Draft");
                }
                else
                {
                    foreach (var item in results.Errors)
                    {
                        ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                    }
                }
            }

            return View();
        }
        public ActionResult Draft()
        {
            string parameter = (string)Session["AdminUserName"];
            var result = mm.GetAllDraft(parameter).Where(x => x.Draft == true).ToList();
            return View(result);
        }

        public ActionResult Delete()
        {
            string parameter = (string)Session["AdminUserName"];
            var result = mm.GetAllDeleted(parameter);
            return View(result);
        }


        public ActionResult IsDeleted(int id)
        {
            var result = mm.GetByID(id);
            if (result.Status == false)
            {
                result.Status = true;
            }
            mm.MessageUpdate(result);
            return RedirectToAction("Delete");
        }

        public ActionResult IsRead(int id)
        {
            var result = mm.GetByID(id);
            result.IsRead = !result.IsRead;
            mm.MessageUpdate(result);
            if (result.IsRead)
            {
                return RedirectToAction("ReadMessage");
            }
            else
            {
                return RedirectToAction("UnReadMessage");
            }
        }

        public ActionResult ReadMessage()
        {
            string parameter = (string)Session["AdminUserName"];
            var readMessage = mm.GetAllRead(parameter).Where(x => x.IsRead == true).ToList();
            return View(readMessage);
        }

        public ActionResult UnReadMessage()
        {
            string parameter = (string)Session["AdminUserName"];
            var unReadMessage = mm.GetAllUnRead(parameter);
            return View(unReadMessage);
        }
    }
}

MvcProjeKampi/Views/Message/Delete.cshtml
@using System.Text.RegularExpressions;
@using EntityLayer.Concrete
@model List<Message>

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">

    <!-- Content Wrapper. Contains page content -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Deleted Message</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            @Html.Action("MessageListMenu", "Contact")
            <!-- /.col -->
            <div class="col-md-9">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">Deleted Message</h3>
                        <div class="card-tools">
                            <div class="input-group input-group-sm">
                                <input type="text" class="form-control" placeholder="Search Mail">
                                <div class="input-group-append">
                                    <div class="btn btn-primary">
                                        <i class="fas fa-search"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <div class="mailbox-controls">
                            <!-- Check all button -->
                            <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                                <i class="far fa-square"></i>
                            </button>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                            </div>
                            <!-- /.btn-group -->
                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                            <div class="float-right">
                                1-50/200
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                </div>
                                <!-- /.btn-group -->
                            </div>
                            <!-- /.float-right -->
                        </div>
                        <div class="table-responsive mailbox-messages">
                            <table class="table table-hover table-striped">
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        item.MessageContent = @Regex.Replace(item.MessageContent, "<.*?>", String.Empty);
                                        <tr>
                                            <td>
                                                <div class="icheck-primary">
                                                    <input type="checkbox" value="" id="check1">
                                                    <label for="check1"></label>
                                                </div>
                                            </td>
                                            <td class="mailbox-star"><a href="/Message/GetInboxMessageDetails/@item.MessageId"><i class="fas fa-star text-warning"></i></a></td>
                                            <td class="mailbox-name"><a href="/Message/GetInboxMessageDetails/@item.MessageId">@item.SenderMail</a></td>
                                            <td class="mailbox-subject">
                                                @if (item.MessageContent.Length < 30)
                                                {
                                                    <b>@item.Subject</b><a> - </a> @item.MessageContent
                                                }
                                                else if (item.MessageContent.Length >= 30)
                                                {
                                                    <span><b>@item.Subject</b> &ndash; @item.MessageContent.Substring(0, item.MessageContent.Substring(0, 30).LastIndexOf(" "))&hellip;</span>

                                                }

                                                @*<b>@item.Subject</b> - @item.MessageContent.Substring(0, 30)*@

                                            </td>
                                            <td class="mailbox-attachment"></td>
                                            <td class="mailbox-date">@(((DateTime)item.MessageDate).ToString("dd-MMM-yyyy"))</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                            <!-- /.table -->
                        </div>
                        <!-- /.mail-box-messages -->
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer p-0">
                        <div class="mailbox-controls">
                            <!-- Check all button -->
                            <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                                <i class="far fa-square"></i>
                            </button>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                            </div>
                            <!-- /.btn-group -->
                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                            <div class="float-right">
                                1-50/200
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                </div>
                                <!-- /.btn-group -->
                            </div>
                            <!-- /.float-right -->
                        </div>
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>

</body>
</html>

MvcProjeKampi/Views/Message/GetInBoxMessageDetails.cshtml
@model EntityLayer.Concrete.Message
@{
    ViewBag.Title = "GetInboxMessagedetails";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>InComing Message Details</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                @Html.Action("MessageListMenu", "Contact")


                <!-- /.col -->
                <div class="col-md-9">
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h3 class="card-title">Read Message</h3>
                            <div class="card-tools">
                                <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Previous"><i class="fas fa-chevron-left"></i></a>
                                <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Next"><i class="fas fa-chevron-right"></i></a>
                            </div>
                        </div>
                        <!-- /.card-header -->



                        <div class="card-body p-0">
                            <div class="mailbox-read-info">
                                <h5>@Html.DisplayFor(x => x.Subject)</h5>
                                <h6>
                                    @Html.DisplayFor(x => x.SenderMail)
                                    <span class="mailbox-read-time float-right">@Model.MessageDate.ToString("dd-MMM-yyyy")</span>
                                </h6>
                            </div>
                            <!-- /.mailbox-read-info -->
                            
                            <!-- /.mailbox-controls -->
                            <div class="mailbox-read-message px-3 pb-2 pt-4">
                                @Html.Raw(Model.MessageContent)
                            </div>
                            <!-- /.mailbox-read-message -->
                        </div>
                        <!-- /.card-footer -->

                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
    </section>
</body>
</html>

MvcProjeKampi/Views/Message/Inbox.cshtml
@using System.Text.RegularExpressions;
@using EntityLayer.Concrete
@model List<Message>

@{
    ViewBag.Title = "Inbox";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@{ string message = "";}
@{ string color = "";}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">

    <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Inbox</h1>
                </div>

            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            @Html.Action("MessageListMenu", "Contact")

            <!-- /.col -->
            <div class="col-md-9">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">InBox</h3>
                        <div class="card-tools">
                            <div class="input-group input-group-sm">
                                @using (Html.BeginForm("Inbox", "Message", FormMethod.Post, new { @class = "form-horizontal" }))
                                {
                                    <div class="input-group">
                                        <input name="p" type="text" class="form-control" placeholder="Search Mail">
                                        <span class="input-group-btn">
                                            <button type="submit" class="btn btn-primary">
                                                <i class="fas fa-search"></i>
                                            </button>
                                        </span>
                                    </div>
                                }
                            </div>
                        </div>
                        <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <div class="mailbox-controls">
                            <!-- Check all button -->
                            <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                                <i class="far fa-square"></i>
                            </button>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                            </div>
                            <!-- /.btn-group -->
                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                            <div class="float-right">
                                1-50/200
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                </div>
                                <!-- /.btn-group -->
                            </div>
                            <!-- /.float-right -->
                        </div>
                        <div class="table-responsive mailbox-messages">
                            <table class="table table-hover table-striped">
                                <tbody>
                                    @foreach (var item in Model)
                                    {

                                        if (item.IsRead == false)
                                        {
                                            message = "Okundu olarak İşaretle";
                                        }
                                        if (item.IsRead == true)
                                        {
                                            message = "Okundu olarak İşaretlendi";
                                        }
                                        if (item.IsRead == false)
                                        {
                                            color = "btn btn-info btn-sm";
                                        }
                                        if (item.IsRead == true)
                                        {
                                            color = "btn btn-danger btn-sm";
                                        }
                                        item.MessageContent = @Regex.Replace(item.MessageContent, "<.*?>", String.Empty);
                                        <tr>
                                            <td>
                                                <div class="icheck-primary">
                                                    <input type="checkbox" value="" id="check1">
                                                    <label for="check1"></label>
                                                </div>
                                            </td>
                                            <td class="mailbox-star"><a href="/Message/IsDeleted/@item.MessageId" id="delete"><i class="far fa-trash-alt text-danger"></i></a></td>
                                            <td class="mailbox-name"><a href="/Message/GetInboxMessageDetails/@item.MessageId">@item.SenderMail</a></td>
                                            <td class="mailbox-subject">

                                                @if (item.MessageContent.Length < 30)
                                                {
                                                    <b>@item.Subject</b><a> - </a> @item.MessageContent
                                                }
                                                else if (item.MessageContent.Length >= 30)
                                                {
                                                    <span><b>@item.Subject</b> &ndash; @Regex.Replace(item.MessageContent, "<.*?>", String.Empty).Substring(0, item.MessageContent.Substring(0, 30).LastIndexOf(" "))&hellip;</span>
                                                }
                                            </td>
                                            <td class="mailbox-attachment"></td>
                                            <td class="mailbox-date"> @(((DateTime)item.MessageDate).ToString("dd-MMM-yyyy"))</td>
                                            <td>
                                                <a class="@color" href="/Message/IsRead/@item.MessageId" id="sign">
                                                    <i class="fas fa-pencil-alt">
                                                    </i>
                                                    @message
                                                    
                                                </a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                            <!-- /.table -->
                        </div>
                        <!-- /.mail-box-messages -->
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer p-0">
                        <div class="mailbox-controls">
                            <!-- Check all button -->
                            <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                                <i class="far fa-square"></i>
                            </button>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-star"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                            </div>
                            <!-- /.btn-group -->
                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                            <div class="float-right">
                                1-50/200
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                </div>
                                <!-- /.btn-group -->
                            </div>
                            <!-- /.float-right -->
                        </div>
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>

</body>
</html>

MvcProjeKampi/Views/Message/NewMessage.cshtml
@model EntityLayer.Concrete.Message

@{
    ViewBag.Title = "NewMessage";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>CUBE | Message Page</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <!-- Theme style -->
    <!-- summernote -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.css">

    @*<script src="~/AdminLTE-3.0.4/plugins/summernote/summernote.min.js"></script>*@
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

</head>
<body class="hold-transition sidebar-mini">

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>New Message</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                @Html.Action("MessageListMenu", "Contact")
                <!-- /.col -->
                <div class="col-md-9">
                    @using (Html.BeginForm("NewMessage", "Message", FormMethod.Post))
                    {
                        <div class="card card-primary card-outline">
                            <div class="card-header">
                                <h3 class="card-title">Yeni Mesaj Oluştur</h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <div class="form-group">
                                    @Html.Label("Alıcı Adı")
                                    @Html.TextBoxFor(x => x.ReceiverMail, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.ReceiverMail)
                                </div>
                                <div class="form-group">
                                    @Html.Label("Konu")
                                    @Html.TextBoxFor(x => x.Subject, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Subject)
                                </div>
                                <div class="form-group">
                                    @Html.Label("Mesajınız")
                                    @Html.TextAreaFor(x => x.MessageContent, new { @class = "form-control", @id = "compose-textarea", @style = "height:300px" })
                                    @*<textarea id="compose-textarea" name="MessageContent" class="form-control" style="height:300px"></textarea>*@
                                    @Html.ValidationMessageFor(x => x.MessageContent)
                                </div>
                                <div class="form-group">
                                    <div class="btn btn-default btn-file">
                                        <i class="fas fa-paperclip"></i> Dosya Ekle
                                        <input type="file" name="attachment">
                                    </div>
                                    <p class="help-block">Max. 32MB</p>
                                </div>
                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <div class="float-right">
                                    <button type="submit" formmethod="post" name="parameter" value="draft" class="btn btn-default" id="draft"><i class="fas fa-pencil-alt"></i> Taslaklara Kaydet </button>
                                    <button type="submit" name="parameter" value="send" class="btn btn-primary" id="added"><i class="far fa-envelope"></i> Gönder </button>
                                </div>
                                <a href="/Message/NewMessage/" class="btn btn-default"><i class="fas fa-times"></i> İptal Et </a>
                                @*<button type="reset" class="btn btn-default"><i class="fas fa-times"></i> İptal Et</button>*@
                            </div>
                            <!-- /.card-footer -->
                        </div>
                    }
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>

    
    <!-- Bootstrap 4 -->

    <!-- AdminLTE App -->
   
    <!-- AdminLTE for demo purposes -->
    
    <!-- Summernote -->
    

    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script>
        $('#added').click(function () {
            swal({
                title: "Gönderildi!",
                text: "Mesaj Başarıyla Gönderildi!",
                icon: "success",
                button: false
            });
        });
    </script>
    <script>
        $('#draft').click(function () {
            swal({
                title: "Eklendi!",
                text: "Taslaklara Eklendi!",
                icon: "success",
                button: false
            });
        });
    </script>
</body>
</html>