MvcProjeKampi/Controllers/AboutController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class AboutController : Controller
    {

        AboutManager abm = new AboutManager(new EfAboutDal());
        // GET: About
        public ActionResult Index()
        {
            var aboutvalues = abm.GetList();
            return View(aboutvalues);
        }
        [HttpGet]
        public ActionResult AddAbout()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddAbout(About p)
        {
            abm.AboutAdd(p);
            return RedirectToAction("Index");
        }

        public PartialViewResult AboutPartial()
        {
            return PartialView();
        }
        public ActionResult DeleteAbout(int id)
        {
            var headingValue = abm.GetByID(id);
            if (headingValue.AboutStatus == true)
            {
                headingValue.AboutStatus = false;
            }

            else
            {
                headingValue.AboutStatus = true;
            }
            abm.AboutDelete(headingValue);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult UpdateAbout(int id)
        {
            var updatevalue = abm.GetByID(id);
            return View(updatevalue);
        }
        [HttpPost]
        public ActionResult UpdateAbout(About about)
        {
            abm.AboutUpdate(about);
            return RedirectToAction("Index");

        }
    }
}

MvcProjeKampi/Controllers/ChartController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class ChartController : Controller
    {
        CategoryManager categoryManager = new CategoryManager(new EfCategoryDal());
        ImageFileManager ımageFileManager = new ImageFileManager(new EfImageFileDal());
        AboutManager aboutManager = new AboutManager(new EfAboutDal());
        // GET: Chart
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Image()
        {
            return View();
        }

        public ActionResult CategoryChart()
        {
            return Json(categoryManager.GetList(), JsonRequestBehavior.AllowGet);
        }
        public ActionResult AboutChart()
        {
            return Json(aboutManager.GetList(), JsonRequestBehavior.AllowGet);
        }
        public ActionResult HeadingChart()
        {
            return Json(ımageFileManager.GetList(), JsonRequestBehavior.AllowGet);
        }


    }
}

MvcProjeKampi/Views/Chart/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("AboutChart", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });
        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'AboutDetails1');
            data.addColumn('number', '1');
            var dataArray = [];
            $.each(result, function (i, obj) {
                dataArray.push([obj.AboutDetails1, 1]);
            });
            data.addRows(dataArray);
            var columnChartOptions = {
                title: "Hakkında - Sayı Grafiği",
                width: 1260,
                height: 800,
                bar: { groupWidth: "20%" },
            };
            var columnChart = new google.visualization.ColumnChart(document
                .getElementById('Columnchart_div'));
            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="Columnchart_div"></div>
</body>
</html>

MvcProjeKampi/Views/Chart/Image.cshtml
@{
    ViewBag.Title = "Image";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("HeadingChart", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });
        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'ImageName');
            data.addColumn('number', '1');
            var dataArray = [];
            $.each(result, function (i, obj) {
                dataArray.push([obj.ImageName, 1]);
            });
            data.addRows(dataArray);
            var columnChartOptions = {
                title: "Resim - Sayı Grafiği",
                width: 1260,
                height: 800,
                bar: { groupWidth: "20%" },
            };
            var columnChart = new google.visualization.LineChart(document
                .getElementById('Linechart_div'));
            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="Linechart_div"></div>
</body>
</html>

MvcProjeKampi/Views/Chart/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("CategoryChart", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });
        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'CategoryName');
            data.addColumn('number', '1');
            var dataArray = [];
            $.each(result, function (i, obj) {
                dataArray.push([obj.CategoryName, 1]);
            });
            data.addRows(dataArray);
            var columnChartOptions = {
                title: "Kategori - Başlık Grafiği",
                width: 1260,
                height: 800,
                bar: { groupWidth: "20%" },
            };
            var pieChart = new google.visualization.PieChart(document
                .getElementById('Piechart_div'));
            pieChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="Piechart_div"></div>
</body>
</html>